//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNotaryWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.PersonDetails = new HashSet<PersonDetail>();
        }
    
        public long ID { get; set; }
        public string Address1 { get; set; }
        public string Street_1 { get; set; }
        public string Street_2 { get; set; }
        public string Street_3 { get; set; }
        public Nullable<long> ZIP { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<PersonDetail> PersonDetails { get; set; }
    }
}
