//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNotaryWebRole.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eNotaryDBEFEntities : DbContext
    {
        public eNotaryDBEFEntities()
            : base("name=eNotaryDBEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Act> Acts { get; set; }
        public DbSet<ActType> ActTypes { get; set; }
        public DbSet<EducationLevel> EducationLevels { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PersonDetail> PersonDetails { get; set; }
        public DbSet<SignedAct> SignedActs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
