//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNotaryWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long ID { get; set; }
        public long SignedActID { get; set; }
        public long PersonID { get; set; }
        public decimal Payment1 { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string ExternalUniqueRefernce { get; set; }
    
        public virtual PersonDetail PersonDetail { get; set; }
        public virtual SignedAct SignedAct { get; set; }
    }
}
