//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNotaryWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignedAct
    {
        public SignedAct()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public long ID { get; set; }
        public long ActID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatePersonID { get; set; }
        public bool Signed { get; set; }
        public string ReasonSigned { get; set; }
        public bool SentToClient { get; set; }
        public string ResonSent { get; set; }
        public string ExternalUniqueReference { get; set; }
    
        public virtual Act Act { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual PersonDetail PersonDetail { get; set; }
    }
}
