//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNotaryWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public long RoleID { get; set; }
        public long PersonID { get; set; }
        public string Username { get; set; }
        public string PsswdEncrypt { get; set; }
        public string DigitalCertificate { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual PersonDetail PersonDetail { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
